version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/
    
before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build ./ServiceBase.sln -c Release /property:Version=$APPVEYOR_BUILD_VERSION
  
test_script:
  - bash coveralls.sh
  
artifacts:
  - path: artifacts\**\*.*
  
cache:
  - '%USERPROFILE%\.nuget\packages'