branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
configuration: Release
build_script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
image: Visual Studio 2015
clone_depth: 1
test: off
deploy: off