version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
clone_depth: 1

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/

configuration: Release
build_script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build .\ServiceBase.sln --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
  - bash coveralls.sh

deploy: off