version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
clone_depth: 1

branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/

configuration: Release
build_script:
  - dotnet --info
  - dotnet restore --no-cache
  - dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
  - dotnet test test/ServiceBase.IdentityServer.Public.UnitTests/project.json --configuration Release -f netcoreapp1.0 --no-build
  - bash coverage.sh
  - bash coveralls.sh

deploy: off