version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
deploy: off
configuration: Release
platform: Any CPU

branches:
  only:
    - master
    - release
    - /^(.*\/)?ci-.*$/

build_script:
  - bash build.sh
  - bash pack.sh

test_script:
  - bash coveralls.sh

deploy: off
